FROM node:22-alpine AS prod

WORKDIR /app

COPY ../package*.json ./

RUN npm ci --production

COPY ../proxy-server.js ./
RUN mkdir -p ./public
COPY ../public/custom-rows.json ./public/
COPY ../public/sample-newsletter.html ./public/

USER node

EXPOSE 3001

CMD ["node", "proxy-server.js"]
